
services:
  api: 
    container_name: blogging_api
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE: ${DATABASE}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_URL: postgres://postgres:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/postgres
      JWT_SECRET: ${JWT_SECRET}
  postgres:
    container_name: blogging_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

volumes:
  postgres:
